server:
  port: ${SERVER_PORT:8761}

eureka:
  instance:
    hostname: ${EUREKA_INSTANCE_HOSTNAME:localhost}
  client:
    registerWithEureka: ${EUREKA_CLIENT_REGISTER_WITH_EUREKA:false}
    fetchRegistry: ${EUREKA_CLIENT_FETCH_REGISTRY:false}
